INSERT INTO cract
           ([codditt]
           ,[ca_codcrac]
           ,[ca_codlead]
           ,[ca_codoppo]
           ,[ca_oggetto]
           ,[ca_codtaco]
           ,[ca_codsatc]
           ,[ca_status]
           ,[ca_opinc]
           ,[ca_note]
           ,[ca_modoppo]
           ,[ca_ultagg]
           ,[ca_opnome]
           ,[ca_dataes]
           ,[ca_oraes]
           ,[ca_tempes]
           ,[ca_libstr1]
           ,[ca_libint1]
           ,[ca_dataprev]
           ,[ca_oraprev]
           ,[ca_opincpr]
           ,[ca_luogo]
           ,[ca_altrep]
           ,[ca_opincpr2]
           ,[ca_opincpr3]
           ,[ca_opincpr4]
           ,[ca_persona]
           ,[ca_servdtua]
           ,[ca_servdeleted]
           ,[ca_clircodcprov]
           ,[ca_clirdeleted]
           ,[ca_clirupdated]
           ,[ca_clirdtua]
           ,[ca_opinc2]
           ,[ca_opinc3]
           ,[ca_opinc4]
           ,[ca_temppr]
           ,[ca_opnomeinc]
           ,[ca_tdtipork]
           ,[ca_tdanno]
           ,[ca_tdserie]
           ,[ca_tdnumord]
           ,[ca_tdvers]
           ,[ca_maimeetinv]
           ,[ca_codcamp]
           ,[ca_organig])
     VALUES
           (@codditt@
           ,@ca_codcrac@
           ,@ca_codlead@
           ,@ca_codoppo@
           ,@ca_oggetto@
           ,@ca_codtaco@
           ,@ca_codsatc@
           ,@ca_status@ 
           ,@ca_opinc@
           ,@ca_note@
           ,@ca_modoppo@ 
           ,@ca_ultagg@
           ,@ca_opnome@
           ,@ca_dataes@
           ,@ca_oraes@
           ,@ca_tempes@
           ,@ca_libstr1@
           ,@ca_libint1@
           ,@ca_dataprev@
           ,@ca_oraprev@
           ,@ca_opincpr@
           ,@ca_luogo@
           ,@ca_altrep@
           ,@ca_opincpr2@
           ,@ca_opincpr3@
           ,@ca_opincpr4@
           ,@ca_persona@
           ,@ca_servdtua@
           ,@ca_servdeleted@ 
           ,@ca_clircodcprov@
           ,@ca_clirdeleted@
           ,@ca_clirupdated@ 
           ,@ca_clirdtua@
           ,@ca_opinc2@
           ,@ca_opinc3@
           ,@ca_opinc4@
           ,@ca_temppr@
           ,@ca_opnomeinc@
           ,@ca_tdtipork@
           ,@ca_tdanno@
           ,@ca_tdserie@ 
           ,@ca_tdnumord@
           ,@ca_tdvers@
           ,@ca_maimeetinv@ 
           ,@ca_codcamp@
           ,@ca_organig@ 
           )

